//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_addition_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_V
    {
        public int Payment_Id { get; set; }
        public string Kullanıcı { get; set; }
        public decimal Tutar { get; set; }
        public System.DateTime SiparisTarihi { get; set; }
        public System.DateTime ÖdemeTarihi { get; set; }
        public string Aciklama { get; set; }
        public int OrderId { get; set; }
    }
}
