//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_addition_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionLevel
    {
        public int Id { get; set; }
        public int RoleId { get; set; }
        public bool canOrder { get; set; }
        public bool canUser { get; set; }
        public bool canTable { get; set; }
        public bool canStock { get; set; }
        public bool canPayment { get; set; }
        public bool canProduct { get; set; }
        public bool canStatistic { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
