//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_addition_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsCategory
    {
        public string UrunAdi { get; set; }
        public decimal Fiyat { get; set; }
        public string KategoriAdi { get; set; }
        public int Id { get; set; }
        public int CategoryId { get; set; }
    }
}
