//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_addition_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisListesi_V
    {
        public int Sipariş_Numarası { get; set; }
        public string Masa_Numarası { get; set; }
        public System.DateTime Tarih { get; set; }
        public decimal Hesap_Toplam_Tutar { get; set; }
        public bool Durum { get; set; }
    }
}
