//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_addition_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMovements_V
    {
        public int Id { get; set; }
        public int StockId { get; set; }
        public int ProductId { get; set; }
        public string UrunAdi { get; set; }
        public bool HareketTuru { get; set; }
        public int Miktar { get; set; }
        public string Birim { get; set; }
        public System.DateTime Tarih { get; set; }
        public string Aciklama { get; set; }
    }
}
